# Generated by Django 5.0.2 on 2024-02-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0002_alter_oplata_ccv_alter_oplata_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Tovar',
        ),
        migrations.DeleteModel(
            name='Zakaz',
        ),
        migrations.AlterField(
            model_name='modal',
            name='year',
            field=models.TextField(verbose_name='Возраст'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
