# Generated by Django 5.0.2 on 2024-02-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0004_zakaz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Tovar',
        ),
        migrations.DeleteModel(
            name='Zakaz',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
