# Generated by Django 5.0.2 on 2024-02-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0005_remove_category_tovar_delete_zakaz_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplata',
            name='ccv',
            field=models.CharField(max_length=3, unique=True, verbose_name='Три цифры'),
        ),
        migrations.AlterField(
            model_name='oplata',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Номер карты'),
        ),
    ]
