# Generated by Django 5.0.4 on 2024-06-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appab', '0028_product_alter_profile_options_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='tovar',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
